#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ChiquitoMarmoraria.Resource", IsApplication=true)]

namespace ChiquitoMarmoraria
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int cardBackgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int cardCornerRadius = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cardElevation = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cardMaxElevation = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int cardPreventCornerOverlap = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int cardUseCompatPadding = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int contentPadding = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int contentPaddingBottom = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int contentPaddingLeft = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int contentPaddingRight = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int contentPaddingTop = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int cardview_dark_background = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int cardview_light_background = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int cardview_shadow_end_color = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int cardview_shadow_start_color = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int cardview_compat_inset_shadow = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int cardview_default_elevation = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int cardview_default_radius = 2131034114;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int calendario = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int logo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int plus = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int recarregar = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int refresh = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08003f
			public const int btnAceitar = 2131230783;
			
			// aapt resource value: 0x7f080076
			public const int btnAdicionar = 2131230838;
			
			// aapt resource value: 0x7f080077
			public const int btnAtualizar = 2131230839;
			
			// aapt resource value: 0x7f080038
			public const int btnCadastrar = 2131230776;
			
			// aapt resource value: 0x7f08005c
			public const int btnCadastrarMaterial = 2131230812;
			
			// aapt resource value: 0x7f080040
			public const int btnCancelar = 2131230784;
			
			// aapt resource value: 0x7f080048
			public const int btnEditar = 2131230792;
			
			// aapt resource value: 0x7f080047
			public const int btnRemover = 2131230791;
			
			// aapt resource value: 0x7f080050
			public const int btnSalvarEdicao = 2131230800;
			
			// aapt resource value: 0x7f080039
			public const int btnVoltar = 2131230777;
			
			// aapt resource value: 0x7f080065
			public const int btn_adicionar = 2131230821;
			
			// aapt resource value: 0x7f080061
			public const int btn_agendamento = 2131230817;
			
			// aapt resource value: 0x7f08005d
			public const int btn_agendamentos = 2131230813;
			
			// aapt resource value: 0x7f080003
			public const int btn_agendar = 2131230723;
			
			// aapt resource value: 0x7f08003e
			public const int btn_alterar = 2131230782;
			
			// aapt resource value: 0x7f080072
			public const int btn_calcular = 2131230834;
			
			// aapt resource value: 0x7f080004
			public const int btn_cancelar = 2131230724;
			
			// aapt resource value: 0x7f08002e
			public const int btn_confirmar = 2131230766;
			
			// aapt resource value: 0x7f080057
			public const int btn_entrar = 2131230807;
			
			// aapt resource value: 0x7f08005a
			public const int btn_facebook = 2131230810;
			
			// aapt resource value: 0x7f080064
			public const int btn_limpar = 2131230820;
			
			// aapt resource value: 0x7f080062
			public const int btn_meusagendamentos = 2131230818;
			
			// aapt resource value: 0x7f080060
			public const int btn_orcamento = 2131230816;
			
			// aapt resource value: 0x7f080016
			public const int btn_proximo = 2131230742;
			
			// aapt resource value: 0x7f080049
			public const int btn_salvar = 2131230793;
			
			// aapt resource value: 0x7f08005e
			public const int btn_solicitacoes = 2131230814;
			
			// aapt resource value: 0x7f08002d
			public const int btn_voltar = 2131230765;
			
			// aapt resource value: 0x7f08004b
			public const int editCategoria = 2131230795;
			
			// aapt resource value: 0x7f08004c
			public const int editDescricao = 2131230796;
			
			// aapt resource value: 0x7f08004a
			public const int editNomeMaterial = 2131230794;
			
			// aapt resource value: 0x7f08004d
			public const int editPreco = 2131230797;
			
			// aapt resource value: 0x7f080000
			public const int imageView1 = 2131230720;
			
			// aapt resource value: 0x7f080045
			public const int imageViewDetalhes = 2131230789;
			
			// aapt resource value: 0x7f080037
			public const int imageViewMaterial = 2131230775;
			
			// aapt resource value: 0x7f08004f
			public const int imagemViewEdicao = 2131230799;
			
			// aapt resource value: 0x7f080007
			public const int img_calendario = 2131230727;
			
			// aapt resource value: 0x7f080054
			public const int img_logo = 2131230804;
			
			// aapt resource value: 0x7f080075
			public const int lblExpenseCancel = 2131230837;
			
			// aapt resource value: 0x7f08006e
			public const int lbl_altura = 2131230830;
			
			// aapt resource value: 0x7f08005f
			public const int lbl_bemvindo = 2131230815;
			
			// aapt resource value: 0x7f080059
			public const int lbl_cadastre = 2131230809;
			
			// aapt resource value: 0x7f080019
			public const int lbl_cep = 2131230745;
			
			// aapt resource value: 0x7f080028
			public const int lbl_complemento = 2131230760;
			
			// aapt resource value: 0x7f080010
			public const int lbl_email = 2131230736;
			
			// aapt resource value: 0x7f080023
			public const int lbl_endereco = 2131230755;
			
			// aapt resource value: 0x7f080058
			public const int lbl_esqueci = 2131230808;
			
			// aapt resource value: 0x7f08001d
			public const int lbl_estado = 2131230749;
			
			// aapt resource value: 0x7f08000d
			public const int lbl_infobasicas = 2131230733;
			
			// aapt resource value: 0x7f080018
			public const int lbl_infocontato = 2131230744;
			
			// aapt resource value: 0x7f08006c
			public const int lbl_largura = 2131230828;
			
			// aapt resource value: 0x7f080055
			public const int lbl_login = 2131230805;
			
			// aapt resource value: 0x7f08006a
			public const int lbl_material = 2131230826;
			
			// aapt resource value: 0x7f080063
			public const int lbl_meuorcamento = 2131230819;
			
			// aapt resource value: 0x7f08000e
			public const int lbl_nome = 2131230734;
			
			// aapt resource value: 0x7f080026
			public const int lbl_numero = 2131230758;
			
			// aapt resource value: 0x7f080070
			public const int lbl_qtd = 2131230832;
			
			// aapt resource value: 0x7f080012
			public const int lbl_senha = 2131230738;
			
			// aapt resource value: 0x7f080014
			public const int lbl_senha_repete = 2131230740;
			
			// aapt resource value: 0x7f08002a
			public const int lbl_telefone = 2131230762;
			
			// aapt resource value: 0x7f080068
			public const int lbl_total = 2131230824;
			
			// aapt resource value: 0x7f080046
			public const int linearLayout1 = 2131230790;
			
			// aapt resource value: 0x7f080005
			public const int linearLayout2 = 2131230725;
			
			// aapt resource value: 0x7f080069
			public const int listaAgendamentos = 2131230825;
			
			// aapt resource value: 0x7f080078
			public const int listaMateriais = 2131230840;
			
			// aapt resource value: 0x7f080067
			public const int listaOrcamentos = 2131230823;
			
			// aapt resource value: 0x7f08001b
			public const int ll_agrupamento3 = 2131230747;
			
			// aapt resource value: 0x7f08001f
			public const int ll_agrupamento4 = 2131230751;
			
			// aapt resource value: 0x7f08002c
			public const int ll_agrupamentoBotoes = 2131230764;
			
			// aapt resource value: 0x7f080022
			public const int ll_agrupamentoEndereco = 2131230754;
			
			// aapt resource value: 0x7f080021
			public const int ll_agrupamentoEnderecoNum = 2131230753;
			
			// aapt resource value: 0x7f080025
			public const int ll_agrupamentoNum = 2131230757;
			
			// aapt resource value: 0x7f08001c
			public const int ll_agrupamento_estado = 2131230748;
			
			// aapt resource value: 0x7f080066
			public const int ll_content = 2131230822;
			
			// aapt resource value: 0x7f08000c
			public const int ll_infoBasic = 2131230732;
			
			// aapt resource value: 0x7f080017
			public const int ll_infoContato = 2131230743;
			
			// aapt resource value: 0x7f080008
			public const int radioGroup1 = 2131230728;
			
			// aapt resource value: 0x7f08000a
			public const int rb_entrega = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int rb_instalacao = 2131230731;
			
			// aapt resource value: 0x7f080009
			public const int rb_medicao = 2131230729;
			
			// aapt resource value: 0x7f080002
			public const int resultAgenda = 2131230722;
			
			// aapt resource value: 0x7f080073
			public const int resultSocilitacoes = 2131230835;
			
			// aapt resource value: 0x7f080041
			public const int scrollView1 = 2131230785;
			
			// aapt resource value: 0x7f080074
			public const int spinnerText = 2131230836;
			
			// aapt resource value: 0x7f08006b
			public const int spn_material = 2131230827;
			
			// aapt resource value: 0x7f08005b
			public const int tableRow1 = 2131230811;
			
			// aapt resource value: 0x7f080001
			public const int textView1 = 2131230721;
			
			// aapt resource value: 0x7f08003b
			public const int textView2 = 2131230779;
			
			// aapt resource value: 0x7f080030
			public const int textView3 = 2131230768;
			
			// aapt resource value: 0x7f08004e
			public const int textView4 = 2131230798;
			
			// aapt resource value: 0x7f080032
			public const int textView5 = 2131230770;
			
			// aapt resource value: 0x7f080034
			public const int textView6 = 2131230772;
			
			// aapt resource value: 0x7f080036
			public const int textView7 = 2131230774;
			
			// aapt resource value: 0x7f080043
			public const int textView8 = 2131230787;
			
			// aapt resource value: 0x7f080044
			public const int textView9 = 2131230788;
			
			// aapt resource value: 0x7f080031
			public const int txtCategoria = 2131230769;
			
			// aapt resource value: 0x7f080033
			public const int txtDescricao = 2131230771;
			
			// aapt resource value: 0x7f080042
			public const int txtNome = 2131230786;
			
			// aapt resource value: 0x7f08002f
			public const int txtNomeMaterial = 2131230767;
			
			// aapt resource value: 0x7f080035
			public const int txtPreco = 2131230773;
			
			// aapt resource value: 0x7f08006f
			public const int txt_altura = 2131230831;
			
			// aapt resource value: 0x7f08001a
			public const int txt_cep = 2131230746;
			
			// aapt resource value: 0x7f080020
			public const int txt_cidade = 2131230752;
			
			// aapt resource value: 0x7f080029
			public const int txt_complemento = 2131230761;
			
			// aapt resource value: 0x7f08003c
			public const int txt_data = 2131230780;
			
			// aapt resource value: 0x7f080051
			public const int txt_descricao = 2131230801;
			
			// aapt resource value: 0x7f080006
			public const int txt_displayData = 2131230726;
			
			// aapt resource value: 0x7f080011
			public const int txt_email = 2131230737;
			
			// aapt resource value: 0x7f080024
			public const int txt_endereco = 2131230756;
			
			// aapt resource value: 0x7f08001e
			public const int txt_estado = 2131230750;
			
			// aapt resource value: 0x7f08006d
			public const int txt_largura = 2131230829;
			
			// aapt resource value: 0x7f080056
			public const int txt_login = 2131230806;
			
			// aapt resource value: 0x7f08000f
			public const int txt_nome = 2131230735;
			
			// aapt resource value: 0x7f080027
			public const int txt_numero = 2131230759;
			
			// aapt resource value: 0x7f080071
			public const int txt_qtd = 2131230833;
			
			// aapt resource value: 0x7f080052
			public const int txt_quantidade = 2131230802;
			
			// aapt resource value: 0x7f080013
			public const int txt_senha = 2131230739;
			
			// aapt resource value: 0x7f080015
			public const int txt_senha_repete = 2131230741;
			
			// aapt resource value: 0x7f08003d
			public const int txt_status = 2131230781;
			
			// aapt resource value: 0x7f08002b
			public const int txt_telefone = 2131230763;
			
			// aapt resource value: 0x7f08003a
			public const int txt_tipo = 2131230778;
			
			// aapt resource value: 0x7f080053
			public const int txt_valor = 2131230803;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AgendamentoAdministrador = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AgendamentoUsuario = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CadastroLogin = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CadastroMateriais = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DetalhesAgendamento = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int DetalhesAgendamentoAdmin = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int DetalhesMaterial = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int EdicaoAgendamentoUsuario = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int EdicaoMaterial = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ItemAgendamento = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ItemOrcamento = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int LoginFacebook = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Main = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int MenuAdministrador = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int MenuUsuario = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int MeuOrcamento = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int MeusAgendamentos = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Orcamento = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int Solicitacoes = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int SppinerItem = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int VisualizacaoMateriais = 2130903060;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070004
			public const int Adicionar = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int ApplicationName = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int Cadastrar = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int Hello = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int Materiais = 2131165186;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Base_CardView = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int CardView = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int CardView_Dark = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int CardView_Light = 2131099651;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
